set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {iSongSelect_IBUF[1]}]
set_property PACKAGE_PIN E3 [get_ports iClk]
set_property PACKAGE_PIN F4 [get_ports iPs2_Clk]
set_property PACKAGE_PIN B2 [get_ports iPs2_Data]
set_property PACKAGE_PIN V10 [get_ports iReset_n]
set_property PACKAGE_PIN A11 [get_ports oPWM]
set_property IOSTANDARD LVCMOS33 [get_ports iClk]
set_property IOSTANDARD LVCMOS33 [get_ports iPs2_Clk]
set_property IOSTANDARD LVCMOS33 [get_ports iPs2_Data]
set_property IOSTANDARD LVCMOS33 [get_ports oPWM]
set_property IOSTANDARD LVCMOS33 [get_ports iReset_n]

set_property IOSTANDARD LVCMOS33 [get_ports oVGA_Hsync]
set_property IOSTANDARD LVCMOS33 [get_ports oVGA_Vsync]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Red[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Red[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Red[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Red[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Green[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Green[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Green[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Green[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Blue[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Blue[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Blue[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oVGA_Blue[0]}]
set_property PACKAGE_PIN D8 [get_ports {oVGA_Blue[3]}]
set_property PACKAGE_PIN D7 [get_ports {oVGA_Blue[2]}]
set_property PACKAGE_PIN C7 [get_ports {oVGA_Blue[1]}]
set_property PACKAGE_PIN B7 [get_ports {oVGA_Blue[0]}]
set_property PACKAGE_PIN A6 [get_ports {oVGA_Green[3]}]
set_property PACKAGE_PIN B6 [get_ports {oVGA_Green[2]}]
set_property PACKAGE_PIN A5 [get_ports {oVGA_Green[1]}]
set_property PACKAGE_PIN C6 [get_ports {oVGA_Green[0]}]
set_property PACKAGE_PIN A4 [get_ports {oVGA_Red[3]}]
set_property PACKAGE_PIN C5 [get_ports {oVGA_Red[2]}]
set_property PACKAGE_PIN B4 [get_ports {oVGA_Red[1]}]
set_property PACKAGE_PIN A3 [get_ports {oVGA_Red[0]}]
set_property PACKAGE_PIN B11 [get_ports oVGA_Hsync]
set_property PACKAGE_PIN B12 [get_ports oVGA_Vsync]

set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Freq[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Freq[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Freq[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Speed[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Speed[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Speed[0]}]
set_property PACKAGE_PIN L16 [get_ports {iControl_Freq[0]}]
set_property PACKAGE_PIN M13 [get_ports {iControl_Freq[1]}]
set_property PACKAGE_PIN R15 [get_ports {iControl_Freq[2]}]
set_property PACKAGE_PIN R17 [get_ports {iControl_Speed[0]}]
set_property PACKAGE_PIN T18 [get_ports {iControl_Speed[1]}]
set_property PACKAGE_PIN U18 [get_ports {iControl_Speed[2]}]

set_property PACKAGE_PIN M17 [get_ports {iControl_Progress[0]}]
set_property PACKAGE_PIN P17 [get_ports {iControl_Progress[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Progress[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iControl_Progress[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_An[0]}]
set_property PACKAGE_PIN U13 [get_ports {oSeg_An[7]}]
set_property PACKAGE_PIN K2 [get_ports {oSeg_An[6]}]
set_property PACKAGE_PIN T14 [get_ports {oSeg_An[5]}]
set_property PACKAGE_PIN P14 [get_ports {oSeg_An[4]}]
set_property PACKAGE_PIN J14 [get_ports {oSeg_An[3]}]
set_property PACKAGE_PIN T9 [get_ports {oSeg_An[2]}]
set_property PACKAGE_PIN J18 [get_ports {oSeg_An[1]}]
set_property PACKAGE_PIN J17 [get_ports {oSeg_An[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSeg_LED[0]}]
set_property PACKAGE_PIN L18 [get_ports {oSeg_LED[7]}]
set_property PACKAGE_PIN T11 [get_ports {oSeg_LED[6]}]
set_property PACKAGE_PIN P15 [get_ports {oSeg_LED[5]}]
set_property PACKAGE_PIN K13 [get_ports {oSeg_LED[4]}]
set_property PACKAGE_PIN K16 [get_ports {oSeg_LED[3]}]
set_property PACKAGE_PIN R10 [get_ports {oSeg_LED[2]}]
set_property PACKAGE_PIN T10 [get_ports {oSeg_LED[1]}]
set_property PACKAGE_PIN H15 [get_ports {oSeg_LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {iSongSelect[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iSongSelect[0]}]
set_property PACKAGE_PIN U12 [get_ports {iSongSelect[1]}]
set_property PACKAGE_PIN U11 [get_ports {iSongSelect[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports oLightsS0]
set_property IOSTANDARD LVCMOS33 [get_ports oLightsS1]
set_property PACKAGE_PIN V12 [get_ports oLightsS0]


set_property PACKAGE_PIN H17 [get_ports oLightsRing]


set_property IOSTANDARD LVCMOS33 [get_ports oLightsRing]


set_property PACKAGE_PIN V14 [get_ports oLightsS1]

set_property IOSTANDARD LVCMOS33 [get_ports oLightsPower]
set_property PACKAGE_PIN V11 [get_ports oLightsPower]
